topCorner/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login,logout


app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.home, name='home' ),
    url(r'^login/$', login, {'template_name':'accounts/login.html'}, name='login' ),
    url(r'^logout/$', logout, {'template_name':'accounts/logout.html'} , name='logout'),


]

topCorner/arsenal/urls.py
from django.conf.urls import url
from arsenal.views import ArsenalView, ArsenalReview

app_name = 'arsenal'

urlpatterns = [
    url(r'^$', ArsenalView.as_view(), name='home'),
    url(r'^review/(?P<pk>\d+)$', ArsenalReview.as_view(), name= 'review'),
]

topCorner/manutd/urls.py
from django.conf.urls import url

# from forms.views import IndexView
# from forms.views import MoviesView, IndexView, Movie_detail
from . import views
from django.shortcuts import render
from manutd.views import ManuView,ManuReview

app_name = 'manutd'

urlpatterns = [
    url(r'^$', ManuView.as_view(), name='home'),
    url(r'^review/(?P<pk>\d+)$', ManuReview.as_view(), name= 'review')

]

topCorner/news/urls.py
from django.conf.urls import url
from .views import IndexView,NewsDetail

app_name = 'news'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^item/(?P<pk>\d+)$', NewsDetail.as_view(), name='detail'),

  
]

topCorner/stadia/urls.py
from django.conf.urls import url

# from forms.views import IndexView
from stadia.views import  IndexView


app_name = 'stadia'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),

]

topCorner/topCorner/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import login
from accounts import views
urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^home/', include('stadia.urls')),
    url(r'^arsenal/', include('arsenal.urls')),
    url(r'^manutd/', include('manutd.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^news/',include('news.urls')),
    url(r'^account/', include('accounts.urls'))
  
]

topCorner/accounts/models.py
from django.db import models

# Create your models here.

topCorner/news/models.py
from django.db import models

# Create your models here.

topCorner/stadia/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone= models.IntegerField(default=0)
def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)


class Team(models.Model):
    name = models.CharField(max_length=200)
    team_logo_url = models.CharField(max_length=100, null=True)
    def __str__(self):
        return self.name

class Pundit(models.Model):
    pundit_name = models.CharField(max_length=200)
    favorite_club = models.ForeignKey(Team, on_delete=models.CASCADE) 
    def __str__(self):
        return self.pundit_name

class Opinion(models.Model):
    reviewer = models.ForeignKey(Pundit, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    game_date = models.DateField(max_length=8, null=True )
    game_review = models.TextField(max_length=1000, null=True)
    logo_url = models.CharField(max_length=100, null=True)
    def __str__(self):
        return self.title

class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

topCorner/arsenal/forms.py
from stadia.models import Opinion,Pundit,Team
from django import forms


class OpinionForm(forms.ModelForm):
    model = Opinion
    fields = []

topCorner/accounts/views.py
from django.shortcuts import render ,HttpResponse,redirect

# Create your views here.

def home(request):
    return render(request, 'accounts/home.html')

def login_redirect(request):
    return redirect('/account/login/')

topCorner/arsenal/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views.generic import FormView, DetailView,View
from django.views.generic.list import ListView
from arsenal.forms import OpinionForm

from stadia.models import Team,Pundit,Opinion


class ArsenalView(ListView):

    template_name = "arsenal/index.html"
    model = Opinion

    def get_queryset(self):
        return Opinion.objects.filter(team__name__icontains='arsenal')

class ArsenalReview(DetailView):
    template_name = "arsenal/reviews.html"
    model = Opinion

topCorner/manutd/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views.generic import FormView, DetailView
from django.views.generic.list import ListView

from stadia.models import Team,Pundit,Opinion


class ManuView(ListView):

    template_name = "manutd/index.html"
    model = Opinion

    def get_queryset(self):
        return Opinion.objects.filter(team__name__icontains='manutd')

class ManuReview(DetailView):
    template_name = "manutd/reviews.html"
    model = Opinion

topCorner/news/views.py
from django.views.generic.list import ListView
from stadia.models import Post
from django.views.generic import DetailView

# Create your views here.

class IndexView(ListView):
    model: Post
    template_name = "news/index.html"
    def get_queryset(self):
        return Post.objects.order_by('published_date')
class NewsDetail(DetailView):
    template_name = "news/item.html"
    model = Post

topCorner/stadia/views.py
from django.views.generic import TemplateView

# Create your views here.
class IndexView(TemplateView):

    template_name = "home.html"

topCorner/templates/accounts/home.html
{% extends 'base.html' %}

{% block title%}Login {% endblock %}

{% block content%}

<br>
<br>
<br>
<br>

<div class="container content">
    
    <h3> Welcome </h3>
    <hr>
        
        <div class="jumbotron bg-info">Welcome 
            <a class="btn btn-danger-outline" href="{% url 'accounts:logout' %}"> Logout <i class="fa fa-power-off" aria-hidden="true"></i></a>
            or 
            <a class="btn btn-danger-outline" href="{% url 'accounts:login' %}"> Register <i class="fa fa-address-book-o" aria-hidden="true"></i></a>
        </div>

</div>





{% endblock %}

topCorner/templates/accounts/login.html
{% extends 'base.html' %} {% block title%}User Login {% endblock %} {% block content%}


<br>
<br>
<br>
<br>
<div class="container content">

    <h3>Login Here</h3>
    <hr>
    <span class="danger">* all fields required </span>
    <form action="" method="POST">
        {% csrf_token %} 
        
        {{ form.as_p }}
        <button type="submit">Login
            <i class="fa fa-power-off" aria-hidden="true"></i>
        </button>
    </form>


</div>
<br> {% endblock %}

topCorner/templates/accounts/logout.html
{% extends 'base.html' %} {% block title%}User Login {% endblock %} {% block content%}


<br>
<br>
<br>
<br>
<div class="container content">

    <h3>Thank you for Visiting Top Corner</h3>
    <br>
    <h4>Tou have been logged out</h4>
   

</div>
<br> {% endblock %}

topCorner/templates/arsenal/base.html
{% load staticfiles %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
    integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
    crossorigin="anonymous">

  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{% static "assets/css/full-slider.css" %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static "assets/theme/css/main.css" type="text/css" %}">
  <link rel="stylesheet" href="{% static "assets\css\full-slider.css" %}">
</head>
  <title>{% block title %}Home{% endblock %} </title>

</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" style=" height: 70px;">
    <div class="container">
      <a class="navbar-brand" href="{% url 'stadia:index' %}">Top Corner</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">

        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'stadia:index' %}">HOME <i class="fa fa-home" aria-hidden="true"></i> <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'news:home' %}">NEWS <i class="fa fa-calendar-check-o" aria-hidden="true"></i></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              TEAMS <i class="fa fa-futbol-o" aria-hidden="true"></i>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

              <a class="dropdown-item" href="{% url 'arsenal:home' %}">ARSENAL</a>
              <a class="dropdown-item" href="{% url 'manutd:home' %}">MANCHESTER UNITED</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:home' %}">LOGIN <i class="fa fa-power-off" aria-hidden="true"></i> </a>
          </li>
        </ul>
      </div>
    </nav>



            {% block content %}
            {% endblock %}





<footer>

    <div class="container">
        <p class="text-xs-center warning">Copyright (c) 2017 Afrotech Frenzy.</p>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
<script src="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-alpha.6.min.js"></script>



  <input name="animation" type="hidden">
  </body>
</html>

topCorner/templates/arsenal/form-template.html
{% for field in form %}

<div class="field">
  <span class="red">{{ field.errors }}</span>
    <label>{{field.label_tag}}</label>

      <div class="field">
        {{ field }}
      </div>

    </div>

{% endfor %}

topCorner/templates/arsenal/index.html
{% extends 'arsenal/base.html' %}
{% block title %} Arsenal  {% endblock %}
{% load staticfiles %}
{% block content %}

<br>
<br>
<br>
<br>
<div class="container">

  <h1>Arsenal Reviews</h1>
  <hr><br><br>
{% for revs in object_list %}



<div class="container">

  <h2>   {{ revs.title }} - {{ revs.game_date }}</h2><a href="{% url 'arsenal:review' pk=revs.pk  %}" class="btn btn-success">Review</a>
<br><hr>

</div>

{% empty %}
<div class="container jumbotron">No Game yet .</div>
{% endfor %}

{% endblock %}
</div>

topCorner/templates/arsenal/opinion_form.html
<div class="ui grid">
    <br>
    <form class="ui form" action="" method="post" enctype="multipart/form-data">
      <legend>Review A Game</legend>
    {% csrf_token %}
    {% include 'arsenal/form-template.html' %}
    
    <button type="submit" name="button" class="ui button">Submit Review</button>
    
    </form>
    
    </div>

topCorner/templates/arsenal/reviews.html
{% extends 'arsenal/base.html' %}
{% block title %} Arsenal {% endblock %}
{% load staticfiles %}
{% block content %}
<br>
<br>
<br>
<br>
<div class="container">

  <br>
  <h1>How it went Down at {{opinion.title}}</h1>
  <hr>
  <img src="{{opinion.logo_url}}" alt="" class="img-responsive" width="350">
    <hr>
  <p>{{opinion.game_review}}</p>
  <a href="{% url 'arsenal:home' %}" class="btn btn-warning">back</a>
</div>
  <hr>
{% endblock %}

topCorner/templates/base.html
{% load staticfiles %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
    integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
    crossorigin="anonymous">

  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{% static "assets/css/full-slider.css" %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static "assets/theme/css/main.css" type="text/css" %}">
  <link rel="stylesheet" href="{% static "assets\css\full-slider.css" %}">
</head>
  <title>{% block title %}Home{% endblock %} </title>

</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" style=" height: 70px;">
    <div class="container">
      <a class="navbar-brand" href="{% url 'stadia:index' %}">Top Corner</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">

        <ul class="navbar-nav ml-auto">
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">REGISTER <i class="fa fa-address-book-o" aria-hidden="true"></i> </a>
          </li>
        </ul>
      </div>
    </nav>



            {% block content %}
            {% endblock %}





<footer>

    <div class="container">
        <p class="text-xs-center warning">Copyright (c) 2017 Afrotech Frenzy.</p>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
<script src="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-alpha.6.min.js"></script>



  <input name="animation" type="hidden">
  </body>
</html>

topCorner/templates/home.html
  {% extends 'arsenal/base.html' %} 
  {% load staticfiles %} 
     
  {% block content %}
      <header>
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <!-- Slide One - Set the background image for this slide in the line below -->
            <div class="carousel-item active" style="background-image: url('http://football-craze.com/wp-content/uploads/2014/09/EPL_Background_Logos.jpg')">
              <!-- <div class="carousel-caption d-none d-md-block">
                        <h3>Home Slide</h3>
                        <p>This is a description for the first slide.</p>
                      </div> -->
            </div>
            <!-- Slide Two - Set the background image for this slide in the line below -->
            <div class="carousel-item" style="background-image: url('http://www.mediaweek.com.au/content/uploads/2016/05/Foxtel-EPL-clubs-logo-1200x600.jpg')">
              <!-- <div class="carousel-caption d-none d-md-block">
                        <h3>Second Slide</h3>
                        <p>This is a description for the second slide.</p>
                      </div> -->
            </div>
            <!-- Slide Three - Set the background image for this slide in the line below -->
            <div class="carousel-item" style="background-image: url('http://www.1sports1.com/wp-content/uploads/2017/08/collage-2017-08-22-1.jpg')">
              <!-- <div class="carousel-caption d-none d-md-block">
                        <h3>Third Slide</h3>
                        <p>This is a description for the third slide.</p>
                      </div> -->
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </header>
  
  <script src="{% static " vendor/jquery/jquery.min.js " %}"></script>
  <script src="{% static " vendor/popper/popper.min.js " %}"></script>
  <script src="{% static " vendor/bootstrap/js/bootstrap.min.js " %}"></script>
  
  {% endblock %}

topCorner/templates/index2.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Full Slider - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "assets/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "assets/css/full-slider.css" rel="stylesheet" %}">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <header>
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <!-- Slide One - Set the background image for this slide in the line below -->
          <div class="carousel-item active" style="background-image: url('http://placehold.it/1900x1080')">
            <div class="carousel-caption d-none d-md-block">
              <h3>First Slide</h3>
              <p>This is a description for the first slide.</p>
            </div>
          </div>
          <!-- Slide Two - Set the background image for this slide in the line below -->
          <div class="carousel-item" style="background-image: url('http://placehold.it/1900x1080')">
            <div class="carousel-caption d-none d-md-block">
              <h3>Second Slide</h3>
              <p>This is a description for the second slide.</p>
            </div>
          </div>
          <!-- Slide Three - Set the background image for this slide in the line below -->
          <div class="carousel-item" style="background-image: url('http://placehold.it/1900x1080')">
            <div class="carousel-caption d-none d-md-block">
              <h3>Third Slide</h3>
              <p>This is a description for the third slide.</p>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </header>

    <!-- Page Content -->
    <section class="py-5">
      <div class="container">
        <h1>Full Slider by Start Bootstrap</h1>
        <p>The background images for the slider are set directly in the HTML using inline CSS. The rest of the styles for this template are contained within the
          <code>full-slider.css</code>file.</p>
      </div>
    </section>

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/popper/popper.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

  </body>

</html>

topCorner/templates/manutd/index.html
{% extends 'arsenal/base.html' %}
{% block title %} Manchester {% endblock %}
{% load staticfiles %}
{% block content %}
<br>
<br>
<br>
<br>

<div class="container">

  <h1>Manchester Reviews</h1>
  <hr><br><br>
{% for revs in object_list %}



<div class="container">

  <h2>   {{ revs.title }} - {{ revs.game_date }}</h2><a href="{% url 'manutd:review' pk=revs.pk  %}" class="btn btn-success">Review</a>
<br><hr>

</div>

{% empty %}
<div class="container jumbotron">No Game yet .</div>
{% endfor %}

{% endblock %}
</div>

topCorner/templates/manutd/reviews.html
{% extends 'arsenal/base.html' %}
{% block title %} Manchester {% endblock %}
{% load staticfiles %}
{% block content %}
<br>
<br>
<br>
<br>
<div class="container">

  <br>
  <h1>How it went Down at {{opinion.title}}</h1>
  <hr>
  <img src="{{opinion.logo_url}}" alt="" class="img-responsive" width="350">
    <hr>
  <p>{{opinion.game_review}}</p>
  <a href="{% url 'arsenal:home' %}" class="btn btn-warning">back</a>
</div>
  <hr>
{% endblock %}

topCorner/templates/news/index.html
{% extends 'arsenal/base.html' %}
{% block title %} News {% endblock %}
{% block content %}
<br>
<br>
<br>
<br>
<div class="row">
    <div class="col-md-4 col-lg-4">
        <img src="https://i.pinimg.com/originals/f4/bd/50/f4bd50ac5488a1fe25cf8e859539ceda.gif" alt="" class="img-responsive">

    </div>
    <div class="col-md-8 col-lg-8 bg-white container">
        <br>
        <h1 class="header">News Items</h1>
        <br> {% for news in object_list %}
        <div class="media-container-row">
            <div class="card col-12 col-md-12 col-lg-12">
                <div class="card-wrapper">
                    <div class="card-img">
                        <img src="assets/images/01.jpg" alt="" media-simple="true">
                    </div>
                    <div class="card-box">
                        <h4 class="card-title mbr-fonts-style display-7">
                            {{ news.title }}
                        </h4>
                        <br>
                        <br>

                        <p class="mbr-text mbr-fonts-style display-7"> {{ news.text}} </p>

                    </div>
                </div>
                <h4 class="warning">{{news.published_date}}</h4>
                <a href="{% url 'news:detail' pk=news.pk  %}" class="btn btn-info">Read More</a>


            </div>
            <br>
            <br> {% empty %}
            <div class="container jumbotron">No Game yet .</div>
            {% endfor %}

        </div>

    </div>
</div>
{% endblock %}

topCorner/templates/news/item.html
{% extends 'arsenal/base.html' %}
{% block title %} News {% endblock %}
{% load staticfiles %}
{% block content %}
<br>
<br>
<br>
<br>
<div class="container">

  <br>
  <h1>{{ post.title }}</h1>
  <hr>
  
  <p>{{post.text}}</p>
  
  <a href="{% url 'news:home' %}" class="btn btn-warning">back</a>
</div>
  <hr>
{% endblock %}

topCorner/templates/sampl.html
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="..\static\assets\theme\css\main.css" type="text/css"> </head>

<body>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <ul class="nav nav-pills">
            <li class="nav-item">
              <a href="#" class="active nav-link"> <i class="fa fa-home fa-home"></i>&nbsp;HOME</a>
            </li>
            <li class="nav-item pull-right">
              <a href="#" class="nav-link">Item</a>
            </li>
          </ul>
        </div>
        <div class="col-md-6">
          <div class="btn-group">
            <button class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown"> TEAMS </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="#" contenteditable="true">Action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#" contenteditable="true">Separated link</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="">TEAM REVIEWS</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <p class="lead">iNTRO ABOUT THE TEAM GOES HERE</p>
        </div>
        <div class="col-md-4">
          <img class="img-fluid d-block" src="https://pingendo.com/assets/photos/wireframe/photo-1.jpg"> </div>
        <div class="col-md-4">
          <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item">
                <img class="d-block img-fluid" src="https://pingendo.com/assets/photos/wireframe/photo-1.jpg" data-holder-rendered="true">
                <div class="carousel-caption">
                  <h3>First slide label</h3>
                  <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                </div>
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ol class="">
            <li>One</li>
            <li>Two</li>
            <li>Three</li>
          </ol>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
  <script src="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-alpha.6.min.js"></script>
</body>

</html>